from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session

from app.schemas.upload import UploadRequest, UploadResponse
from app.schemas.query import QueryRequest, QueryResponse, OfferEvaluation
from app.schemas.version import VersionResponse
from app.core.config import API_VERSION, API_NAME, API_DESCRIPTION
from app.core.db import get_db
from app.services.ingestion_service import ingest_quotation

router = APIRouter()


@router.post("/upload", response_model=UploadResponse)
def upload_quotation(
    payload: UploadRequest,
    db: Session = Depends(get_db),
) -> UploadResponse:
    """
    Ingest a raw supplier quotation.

    Current behaviour:
    - Generate a placeholder embedding
    - Store quotation in the database
    - Return the new quotation ID and a confirmation message

    Later:
    - Use ExtractorAgent to parse structured fields from the text
    - Generate real embeddings from an embedding model
    - Persist fully structured quotation + embedding
    """
    quotation = ingest_quotation(payload.text, db)

    return UploadResponse(
        id=quotation.id,
        message="Quotation ingested successfully",
    )


@router.post("/query", response_model=QueryResponse)
async def query_text(payload: QueryRequest) -> QueryResponse:
    """
    Skeleton endpoint for querying the system with a natural language request.

    Currently returns a static example response. Later, this will:
    - run retrieval over stored quotations using vector similarity
    - evaluate offers via a multi-agent chain
    - return a real recommendation and grounded reasoning
    """

    # TEMP: example-like static response just to prove the shape works
    offers = [
        OfferEvaluation(
            supplier="QuickFix",
            item="10mm steel bolt (SB-10)",
            unit_price=0.75,
            delivery_days=10,
            risk_assessment="Low Risk (Reliable supplier, 95% on-time delivery)",
        ),
        OfferEvaluation(
            supplier="Premier Metals",
            item="10mm steel bolt (SB-10)",
            unit_price=0.70,
            delivery_days=8,
            risk_assessment="High Risk (Major quality issues last year, be cautious)",
        ),
    ]

    return QueryResponse(
        recommendation="QuickFix",
        reasoning=(
            "Static placeholder: in the final system this will be generated by the "
            "evaluation agent based on retrieved offers and risk signals."
        ),
        offers_evaluated=offers,
    )


@router.get("/version", response_model=VersionResponse, tags=["meta"])
def get_version() -> VersionResponse:
    """
    Return basic API version metadata.
    """
    return VersionResponse(
        version=API_VERSION,
        name=API_NAME,
        description=API_DESCRIPTION,
    )
