from fastapi import APIRouter
from app.schemas.upload import UploadRequest, UploadResponse
from app.schemas.query import QueryRequest, QueryResponse, OfferEvaluation

router = APIRouter()

@router.post("/upload", response_model=UploadResponse)
async def upload_text(payload: UploadRequest):
    """
    Skeleton endpoint for querying supplier offers.

    Later:
    - Retrieve embedded vectors from pgvector
    - Pass supplier/product/question into multi-agent chain
    - Return evaluated answer + justification
    """

    text_length = len(payload.text)

    return UploadResponse(
        message="Text received successfully. Processing not implemented yet",
        length=text_length,
    )

@router.post("/query", response_model=QueryResponse)
async def query_text(payload: QueryRequest):
    """
    Skeleton endpoint for querying the system with a natural language request.

    Currently returns a static example response. Later, this will:
    - run retrieval over stored quotations
    - evaluate offers via multi-agent chain
    - return a real recommendation and reasoning
    """

    # TEMP: example-like static response just to prove the shape works
    offers = [
        OfferEvaluation(
            supplier="QuickFix",
            item="10mm steel bolt (SB-10)",
            unit_price=0.75,
            delivery_days=10,
            risk_assessment="Low Risk (Reliable supplier, 95% on-time delivery)",
        ),
        OfferEvaluation(
            supplier="Premier Metals",
            item="10mm steel bolt (SB-10)",
            unit_price=0.70,
            delivery_days=8,
            risk_assessment="High Risk (Major quality issues last year, be cautious)",
        ),
    ]

    return QueryResponse(
        recommendation="QuickFix",
        reasoning=(
            "Static placeholder: in the final system this will be generated by the "
            "evaluation agent based on retrieved offers and risk signals."
        ),
        offers_evaluated=offers,
    )
